### ISSUE TITLE
Syntax errors break input

### ISSUE THREAD

**Issue by kaiw** [nathan-hoad/aiomanhole#2]
If you ever enter a syntax error into the manhole, it breaks the session, because it treats a syntax error as an incomplete multi-line command.

```
>>> reee reee
... 
... 
... 
... what
... 
```

**Comment by nathan-hoad** [comment]
:v

**Comment by nathan-hoad** [comment]
I'm horrible and didn't do a "fixes" type dealie in my commit message, but this is fixed in 0.4.0. Thank you for your report, citizen!
